---

- name: Activate mod rewrite
  apache2_module: state=present name=rewrite
  notify: start apache

- name: Create 000-default.conf
  template: src=000-default.conf.j2
    dest=/etc/apache2/sites-available/000-default.conf
    owner=root
    group=root
    mode=0644
  notify:
    - restart apache
    - restart mysql