---

- name: Create the dedicated OS user (matching the original DB user) for executing the SMW restore process
  user: name={{lsdr_restoring_os_user}}

- name: Copy GPG public key
  copy: content="{{lsdr_public_gpg_key}}" dest=/tmp/lsdr_public_gpg_key.gpg

- name: Copy GPG secret key
  copy: content="{{lsdr_secret_gpg_key}}" dest=/tmp/lsdr_secret_gpg_key.gpg

- name: Install GPG public key for {{lsdr_restoring_os_user}}
  shell: gpg --import lsdr_public_gpg_key.gpg
    chdir=/tmp
  become: true
  become_user: "{{lsdr_restoring_os_user}}"
  ignore_errors: yes

- name: Install GPG secret key for {{lsdr_restoring_os_user}}
  shell: gpg --allow-secret-key-import --import lsdr_secret_gpg_key.gpg
    chdir=/tmp
  become: true
  become_user: "{{lsdr_restoring_os_user}}"
  ignore_errors: yes
