---

- include: create_dedicated_restoring_os_user.yml
- include: create_dedicated_database_and_user.yml
- include: create_restore_environment.yml
- include: move_restore_into_apache_root_and_configure.yml
- include: configure_apache.yml