---

- name: Copy the restored SMW root into the Apache root
  shell: cp --recursive {{lsdr_restored_smw_root}}/* {{lsdr_apache_smw_root}}/

- name: Adapt permissions for/in {{lsdr_apache_smw_root}}
  file: path={{lsdr_apache_smw_root}}
    state=directory
    owner={{lsdr_restoring_os_user}}
    group=www-data
    recurse=yes
    mode=770
