---

- name: start apache
  service: name=apache2 state=started

- name: restart apache
  service: name=apache2 state=restarted

- name: start mysql
  service: name=mysql state=started

- name: restart mysql
  service: name=mysql state=restarted